FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY target/SleepSOAPAdapter-0.0.1-SNAPSHOT.jar SleepSOAPAdapter-0.0.1-SNAPSHOT.jar

EXPOSE 8089

CMD ["java", "-jar", "SleepSOAPAdapter-0.0.1-SNAPSHOT.jar"]