services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8087:8087"
    depends_on:
      - coffee-service

  coffee-service:
    build: ./coffee-service
    container_name: coffee-service
    ports:
      - "8080:8080"
