services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8087:8087"
    depends_on:
      - coffee-service
      - rate-service

  coffee-service:
    build: ./coffee-service
    container_name: coffee-service
    ports:
      - "8080:8080"

  sleep-service:
    build: ./sleep-service
    container_name: sleep-service
    ports:
    - "8082:8082"

  rate-service:
    build: ./rate-service
    container_name: rate-service
    ports:
      - "8084:8084"

  humor-service:
    build: ./humor-service
    container_name: humor-service
    ports: 
      - "8085:8085"

  humor-adapter:
    build: ./humor-adapter
    container_name: humor-adapter
    ports:
      - "8088:8088"
  
  advice-coffee-service:
    build: ./advice-coffee-service
    container_name: advice-coffee-service
    ports:
    - "8081:8081"
