FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY target/AdviceMoodSOAPAdapter-0.0.1-SNAPSHOT.jar AdviceMoodSOAPAdapter-0.0.1-SNAPSHOT.jar

EXPOSE 8090

CMD ["java", "-jar", "AdviceMoodSOAPAdapter-0.0.1-SNAPSHOT.jar"]