server:
  port: 8087
  
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: coffee
              uri: http://coffee-service:8080
              predicates:
              - Path=/api/coffee/**
              filters:
              - RewritePath=/api/coffee/(?<segment>.*), /CoffeeTrackerRESTServiceMaven/coffee/${segment}